FROM jekyll/jekyll:latest

ARG JEKYLL_ENV

# throw errors if Gemfile has been modified since Gemfile.lock
RUN bundle config --global frozen 1

WORKDIR /usr/src/app

COPY blog/Gemfile Gemfile.lock ./

RUN bundle install

COPY blog .

RUN jekyll build

CMD ["entry_point.sh"]
