# Site
name: "Drive Today"
title: "Drive Today"
description: "All things driving, reviews and great content."
logo: 'assets/images/dt-rect.png'
favicon: 'assets/images/dt.ico'
baseurl: ''
google_analytics: 'G-TEPW01EEMR'
disqus: 'demowebsite'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
email: info@drivetoday.uk

# Authors
authors:
  ry:
    name: Ryan Dutton
    display_name: ryan
    avatar: assets/images/avatar.png
    email: rl.dutton@icloud.com
    web: https://twitter.com/thedrivetoday # https://scorzer.co.uk
    twitter: https://twitter.com/thedrivetoday
    description: "Author of Drive Today, Ride Today, and Scorzer."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
#highlighter: none
#markdown: kramdown
#kramdown:
#   syntax_highlighter_opts:
#      disable : true

lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge


# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
